# Generated by Django 5.1.4 on 2025-01-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_drink_drink_cost_drink_drink_cost_12oz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=10)),
                ('size_cost', models.FloatField(default=1.0)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.drink')),
            ],
        ),
    ]
