# Generated by Django 5.1.4 on 2025-01-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_drink_drink_name_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drink_cost_12oz',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='drink_cost_16oz',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='drink_cost_20oz',
        ),
    ]
