# Generated by Django 5.1.4 on 2025-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_drink_drink_cost_12oz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=20),
        ),
    ]
